settings:
  title: 'Status Page'
  url: 'https://status.furst.io' # used for Slack messages
  logo: favicon.ico # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: furst-io # unique identifier
    name: furst.io
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://furst.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: bitwarden-furst-io
    name: bitwarden.furst.io
    description: 'Built for anything connected to the Internet.'
    url: 'https://bitwarden.furst.io'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
